package PB_2015_2.Main;

public enum Methods {
	OPEN, SET_PREF_EXPORT_PATH, EXPORT_IP_ADDR, DEL_IP_ADDR_IN_NE, VER_IP_ADDR_DELETED, IMPORT_IP_ADDR, VER_IP_ADDR_IMPORTED, IMPORT_COMP_IN_NE_GROUP, DEL_UDSV, DEL_VBZ, DEL_SITE_ROOM, DEL_SITE, CLOSE, SCRIPT_PARAM,
	R_CREATE_STORD_ENSEMBLE_5119,R_ABM_ORDER_CYC_3115,    	
	R_ABM_ORDER_CYC_4851,    	
	FB_ABM_ORDER_DEL_4851,   	
	R_ABM_ORDER_DEL_VERI_4851,	
	R_ORD_CYC_REP_3031,			
	R_CREATE_NE_ENSAMBLE_5112,
	CREATE_VBZs_REL_1_N_4880,
	CHG_ENDPT_MULT_VBZs_REL_1_N_4879,
	CREATE_eStoB_NE_4909, 
	CONF_EXCHANGE_4138 	
}
